language: java

jdk:
  - oraclejdk7
  - openjdk6

install: mvn clean install --fail-never --quiet -DskipTests=true -Dinvoker.skip=true

script: mvn clean verify

after_success:
  - .buildscript/deploy_snapshot.sh

notifications:
  email: true

sudo: false

cache:
  directories:
    - $HOME/.m2
